// This file should not be edited anymore since a stable version refers to it (except
// maybe for purely visual things that don't change the goals, like typos).


var bingoList_Pal_v1 = [

// Very Easy (0)
[
	{name: "(2-4) Lamballs"},
	{name: "(200-300) Wood"}, //Grow a Tree in the Nether
	{name: "(5-10) Lifmunk Effigies", antisynergy:"Effigies"}, //(5-8) Colours of Terracotta
	{name: "(24-25) Eggs", antisynergy:"eggs"}, //(1-5) Mushroom Stew
	{name: "Shoot a merchant with an Arrow"},
	{name: "Make the Bowler Hat"}, //Make a sign
	{name: "(5-10) Fuack"},
	{name: "(100-200) cooked red berries"}, //Cake
	{name: "(200-300) Stone"},
	{name: "Fish a Treasure and Junk item"},
	{name: "(2-5) Fuack"},
	{name: "(2-5) Chikipi"},
	{name: "(2-5) Cattiva"},
	{name: "(2-5) Sparkit"},
	{name: "(2-5) Vixy"},
	{name: "(20-30) Ore", antisynergy: "ingot", infrequency: 2},
	{name: "(20-30) Sulfur ", antisynergy: "sulfur", infrequency: 2},
	{name: "Full Set of Stone tools"},
	{name: "Be a Nudist(Don't wear outfits)",antisynergy: "Outfits", infrequency: 5},
	{name: "Feathered Hair Band"},
	{name: "Build a (2-4)x(2-4)x(2-4) house", tooltiptext: "You can choose what shall be the width/length/height.", tooltipimg: "Goal Tooltip Images/LeafCube.jpg"},
	{name: "Level (10-12)",antisynergy: "Level", infrequency: 4},
	{name: "(5-25) Wool & (5-25) Leather",antisynergy: "wool"},
	{name: "(4-5) Fast travel points"},
	{name: "Never Sleep", antisynergy: "Sleep"},
	{name: "(15-35) Wool",antisynergy: "wool"},
	{name: "(1-3) Gunpoweder",infrequency: 10 ,antisynergy: "gunpoweder"},
	{name: "(5-15) Pal Fluid"},
	{name:"Find the location ine the photo", tooltiptext:"Find this location", tooltipimg: "Goal Tooltip Images/Location1.png"}



],

// Easy (1)
[
	{name: "(2-4) Different Water types"},
	{name: "(2-4) Make a sign"},
	{name: "Cannot eat Veg or fruit", antisynergy:"meat",tooltiptext: "You can only eat Meat", infrequency: 4},
	{name: "Vegan Diet only", antisynergy:"meat",tooltiptext: "You can only eat fruit or veg", infrequency: 4},
	{name: "Grilled Galeclaw",infrequency: 4},
	{name: "Kill a Alpha pal", antisynergy:"AlphaPal"},
	{name: "Crossbow"},
	{name: "Cake",antisynergy:"cake"},
	{name: "Collect 3 Sphere types", antisynergy:"Spheres"},
	{name: "(20-30) Lifmunk Effigies",antisynergy:"Effigies"},
	{name: "(50-100) Eggs",antisynergy:"eggs"},
	{name: "Catch something in a hanging trap"},
	{name: "Craft Normal Parachute", antisynergy: "Parachute"},
	{name: "Cannot fly using parachute", antisynergy: "Parachute",tooltiptext: "You can still fly or glide with pals", infrequency: 2},
	{name: "World has to be normal difficulty or above",antisynergy:"difficulty"},
	{name: "Open 5 chests"},
	{name: "Pals can only build and craft",antisynergy:"Palcrafting",infrequency: 10},
	{name: "Never use a Shield"},
	{name: "Be a Nudist(Don't wear outfits)",antisynergy: "Outfits", infrequency: 5},
	{name: "Craft uncommon armor/outfit"},
	{name: "Rescue a Pal!",tooltiptext: "Save a Pal from a Outposts"},
	{name: "Level (10-15)", antisynergy: "Level", infrequency: 4},
	{name:"Find the location ine the photo", tooltiptext:"Find this location", tooltipimg: "Goal Tooltip Images/location2.jpg"},
	{name: "(3-5) Different Edible Items",antisynergy: "Edible Items"},
	
	// {name: "Create a Snow Golem"},
	// {name: "(5-15) Note Blocks", antisynergy: "NoteBlocks", infrequency: 2},
	// {name: "(5-15) Ink Sacks", antisynergy: "InkSacks", infrequency: 2},
	// {name: "(6-10) Bread", antisynergy: "Bread", infrequency: 2},
	// {name: "(2-3) Hay Bales", antisynergy: "HayBale", infrequency: 2},
	// {name: "(5-8) Colours of Wool", antisynergy: "WoolColour", infrequency: 4},
	// {name: "(5-10) Pistons"},
	// {name: "Full Iron Armour"},
	// {name: "Full Leather Armour"},
	// {name: "Full Gold Armour"},
	// {name: "Cauldron with Water"},
	// {name: "Complete a Map"},
	// {name: "(16-64) Soul Sand"},
	// {name: "(5-10) Pumpkins"},
	// {name: "(10-30) Vines"},
	// {name: "(5-7) Different Slabs", antisynergy: "Slabs", infrequency: 2},
	// {name: "Every type of Sword"},
	// {name: "Every type of Pickaxe"},
	// {name: "(16-64) Brick Blocks"},
	// {name: "(16-32) Nether Brick Blocks"},
	// {name: "(16-64) Arrows"},
	// {name: "Sleep in the Nether", reactant: "Sleep"},
	// {name: "Fermented Spider Eye"},
	// {name: "(5-7) Different Stairs", antisynergy: "Stairs", infrequency: 2},
	// {name: "(2-4) Ender Pearls"},
	// {name: "16 Chicken Eggs"},
	// {name: "Hang up 3 Different 4x4 Paintings"},
	// {name: "(5-10) Bone Blocks"},
	// {name: "2 Creepers in the same Boat", tooltiptext: "The 2 Creepers must be in the same boat at the same time", tooltipimg: "Goal Tooltip Images/2creepers1boat.jpg"},
	// {name: "Trade with a Villager"},
	// {name: "(2-3) Different Pattern / Colour Shields"},
	// {name: "Dead Bush"},
	// {name: "(5-15) Grass", tooltiptext: "The tall stuff, NOT the block", tooltipimg: "Goal Tooltip Images/TallGrass.jpg"},
	// {name: "Cyan Dye", infrequency: 10},
	// {name: "Light Gray Dye and Light Blue Dye", infrequency: 10},
	// {name: "Magenta Dye", infrequency: 10},
	// {name: "Rose Red", infrequency: 10},
	// {name: "Orange Dye", infrequency: 10},
	// {name: "Dandelion Yellow", infrequency: 10},
	// {name: "Cactus Green", infrequency: 10},
	// {name: "Pink Dye", infrequency: 10},
	// {name: "Purple Dye", infrequency: 10},
	// {name: "Lime Dye", infrequency: 10},
	// {name: "Never Sleep", catalyst: "Sleep"},
	// {name: "Grow a Huge Mushroom"},
	// {name: "Water Bucket, Lava Bucket and Milk Bucket"},
	// {name: "(3-6) Different Flowers", antisynergy: "Flowers", infrequency: 3},
	// {name: "(3-6) Colours of Concrete", antisynergy: "ConcreteColour", infrequency: 4},
	// {name: "(3-6) Colours of Glazed Terracotta", antisynergy: "GlazedColour", infrequency: 4},
	// {name: "(3-6) Colours of Beds", antisynergy: "BedColour", infrequency: 4},
	// {name: "Finish where you spawned using a Compass", tooltiptext: "Be stood close enough to spin your compass within a couple blocks at the end of the game", tooltipimg: "Goal Tooltip Images/Compass.jpg", antisynergy: "Finish"},
	// {name: "Build a Redstone AND Gate"},
	// {name: "(32-64) Stone", tooltiptext: "NOT Cobblestone, normal Stone", tooltipimg: "Goal Tooltip Images/Stone.jpg", antisynergy: "Stone", infrequency: 2},
	// {name: "Kill (4-8) Animals with only fire"},
	// {name: "Kill a Creeper with only fire"},
	// {name: "(32-64) Iron Nuggets"},
	// {name: "(32-64) Gold Nuggets"},
	// {name: "(16-32) Rotten Flesh", antisynergy: "RotFlesh", infrequency: 2},
	// {name: "(33-64) Redstone", antisynergy: "Redstone", infrequency: 2},
],

// Medium (2)
[
	{name:"Pals can only build and craft",antisynergy:"Palcrafting",infrequency: 5},
	{name:"Finish by jumping form height limit", tooltiptext: "Build up height limit, and then jump from top to bottom at the end of the game", tooltipimg: "Goal Tooltip Images/FinishTopToBottom.jpg", antisynergy: "Finish"},
	{name: "Capture a Human"},
	{name: "(3-5) Different metal Items"},
	{name: "Collect 2 ridable mounts", tooltiptext:"Need to be rideable as in have the saddle as well"},
	{name: "(3-5) Cake", antisynergy:"cake"},
	{name: "(2-5) Galeclaw"},
	{name: "(3-4) Kill Alpha pals", antisynergy:"AlphaPal"},
	{name: "(40-50) Lifmunk Effigies", antisynergy:"Effigies"},
	{name: "level (8-10) base", antisynergy:"Bases"},
	{name: "(6-8) Different Edible Items",antisynergy: "Edible Items"},
	
	{name: "Cookie"},
	{name: "Very Damaged Anvil"},
	{name: "(16-64) Melons (Slices)"},
	{name: "Sleep inside a village", reactant: "Sleep"},
	{name: "Kill a Skeleton with its own Arrow"},
	{name: "Never wear any Armour", catalyst: "WearArmour"},
	{name: "Get a Skeleton's Bow", tooltiptext: "Kill Skeletons until you get a rare drop from one, it being their Bow"},
	{name: "Diamond Block", antisynergy: "DiamondBlock", infrequency: 2},
	{name: "(2-3) Lapis Lazuli Blocks"},
	{name: "Destroy a Monster Spawner"},
	{name: "(2-5) Different Saplings"},
	{name: "Tame an Ocelot"},
	{name: "Tame a Wolf"},
	{name: "9 Fire Charges"},
	{name: "(1-3) Magma Cream"},
	{name: "Grow a Full Jungle Tree"},
	{name: "Create an Iron Golem"},
	{name: "Eye of Ender"},
	{name: "Rabbit Stew"},
	{name: "Potion of Fire Resistance", infrequency: 9},
	{name: "Potion of Healing", infrequency: 9},
	{name: "Potion of Poison", infrequency: 9},
	{name: "Potion of Harming", infrequency: 9},
	{name: "Potion of Regeneration", infrequency: 9},
	{name: "Potion of Slowness", infrequency: 9},
	{name: "Potion of Strength", infrequency: 9},
	{name: "Potion of Swiftness", infrequency: 9},
	{name: "Potion of Weakness", infrequency: 9},
	{name: "Finish by jumping from top to bottom of the world", tooltiptext: "Dig a hole to bedrock, build up to 256 Y (height limit), and then jump from top to bottom at the end of the game", tooltipimg: "Goal Tooltip Images/FinishTopToBottom.jpg", antisynergy: "Finish"},
	{name: "Vegetarian", tooltiptext: "Never eat meat, including fish", tooltipimg: "Goal Tooltip Images/NoFish.jpg", antisynergy: "Food"},
	{name: "Carnivore", tooltiptext: "Only eat meat", tooltipimg: "Goal Tooltip Images/NoBread.jpg", antisynergy: "Food"},
	{name: "Kill yourself with your own arrow", reactant: "Death"},
	{name: "Get a '... while trying to escape ...' Death message", tooltiptext: "Example: 'PLAYER' drowned while trying to escape a Skeleton", reactant: "Death"},
	{name: "Set fire to a Villager's House"},
	{name: "Finish on top of the world", tooltiptext: "Build up to 256 Y (the height limit) and stand on the top at the end of the game", tooltipimg: "Goal Tooltip Images/FinishTop.jpg", antisynergy: "Finish"},
	{name: "Kill a mob with Gravel/Sand"},
	{name: "Put a Carpet on a Llama"},
	{name: "Activate a (4-6)x(4-6) Nether Portal (not counting corners)", tooltiptext: "Width/height of the obsidian frame, disregarding corners (or in other words, width/height of the - once activated - purple portal area).", tooltipimg: "Goal Tooltip Images/Portal.jpg"},
	{name: "(5-10) Obsidian"},
	{name: "(5-7) Iron Blocks", antisynergy: "IronBlocks", infrequency: 2},
	{name: "(3-4) Gold Blocks", antisynergy: "GoldBlocks", infrequency: 2},
	{name: "Daylight Sensor"},
	{name: "Enchanted Golden Sword"},
	{name: "(9-12) Colours of Wool", antisynergy: "WoolColour", infrequency: 4},
	{name: "(8-11) Colours of Terracotta", antisynergy: "TerracottaColour", infrequency: 4},
	{name: "(7-10) Colours of Glazed Terracotta", antisynergy: "GlazedColour", infrequency: 4},
	{name: "(7-10) Colours of Concrete", antisynergy: "ConcreteColour", infrequency: 4},
	{name: "(7-10) Colours of Beds", antisynergy: "BedColour", infrequency: 4},
	{name: "Power a Redstone Lamp"},
	{name: "(7-10) Different Flowers", antisynergy: "Flowers", infrequency: 3},
	{name: "Put a Pigman in Water"},
	{name: "Place an Iron, Gold and Diamond block on top of each other"},
	{name: "Kill a hostile mob with an Anvil"},
	{name: "Never Die", catalyst: "Death"},
	{name: "Level (16-26)", antisynergy: "Level", infrequency: 4},
	{name: "(2-3) Different Seeds", antisynergy: "Seeds", tooltiptext: "Includes Nether Wart and Cocoa Beans"},
	{name: "Dig a 1x1 hole to bedrock (from sea level)"},
	{name: "Wear 4 Different Armour types at the same time",  tooltiptext: "Example: GOLD shoes, LEATHER Trousers, IRON Chestplate and DIAMOND Helmet", tooltipimg: "Goal Tooltip Images/4Armour.jpg", reactant: "WearArmour"},
	{name: "Fill a Hopper with 320 items"},
	{name: "(16-32) Red Nether Brick Blocks"},
	{name: "(16-32) Spectral Arrows"},
	{name: "Activate a Nether Portal inside of a Village"},
	{name: "(33-64) Rotten Flesh", antisynergy: "RotFlesh", infrequency: 2},
	{name: "(16-32) Ink Sacks", antisynergy: "InkSacks", infrequency: 2},
],

// Hard (3)
[
	{name: "Cannot craft Palshperes (no Pals crafting them either)", tooltiptext: "There might be otherways to get them"},
	{name: "craft a rare outfit"},
	{name: "Give a Pal a gun"},
	{name: "Climb the highest mountain in the game"},
	
	{name: "Shear a Mooshroom"},
	{name: "Sea Lantern"},
	{name: "Sponge", tooltiptext: "DRY Sponge, not a wet one", tooltipimg: "Goal Tooltip Images/Sponge.jpg"},
	{name: "Bounce on a Slime Block", tooltiptext: "Get a Slime Block, place it on the ground and give it a good old bouncin' on", tooltipimg: "Goal Tooltip Images/SlimeBlock.jpg"},
	{name: "Listen to a Music Disc"},
	{name: "(11-14) Different Flowers", antisynergy: "Flowers", infrequency: 3},
	{name: "3 Diamond Blocks", antisynergy: "DiamondBlock", infrequency: 2},
	{name: "Get a Zombie Pigman's Sword", tooltiptext: "Kill Pigmen until you get a rare drop from one, it being their Golden Sword", tooltipimg: "Goal Tooltip Images/GoldenSword.jpg"},
	{name: "Finish by launching Fireworks of (5-10) Different Colours", antisynergy: "Finish"},
	{name: "Nametag an Enderman"},
	{name: "Kill yourself with an Ender Pearl", tooltiptext: "Need to die to the small fall damage taken from using a pearl", tooltipimg: "Goal Tooltip Images/EnderPearl.jpg", reactant: "Death"},
	{name: "Finish on top of a Blaze spawner", tooltiptext: "Be stood on top of a Blaze spawner at the end of the game", antisynergy: "Finish"},
	{name: "(13-16) Colours of Wool", antisynergy: "WoolColour", infrequency: 4},
	{name: "(12-15) Colours of Terracotta", antisynergy: "TerracottaColour", infrequency: 4},
	{name: "(11-14) Colours of Glazed Terracotta", antisynergy: "GlazedColour", infrequency: 4},
	{name: "(11-14) Colours of Concrete", antisynergy: "ConcreteColour", infrequency: 4},
	{name: "(11-14) Colours of Beds", antisynergy: "BedColour", infrequency: 4},
	{name: "Poison a Parrot"},
	{name: "Tame a Parrot"},
	{name: "Kill an Iron Golem"},
	{name: "Place an Ice Block on top of a Magma Block"},
	{name: "Level (27-37)", antisynergy: "Level", infrequency: 4},
	{name: "Build a (2-4)x(2-4)x(2-4) Ice cube", tooltiptext: "You can choose what shall be the width/length/height.", tooltipimg: "Goal Tooltip Images/IceCube.jpg"},
	{name: "(4-5) Different Seeds", antisynergy: "Seeds", tooltiptext: "Includes Nether Wart and Cocoa Beans"},
	{name: "Finish on top of a stairway to Heaven", tooltiptext: "Using Stairs, build up to 256 Y (the height limit) and stand on the top at the end of the game (If you need to jump over a block to go from bottom to top, it's not a finished stairway)", tooltipimg: "Goal Tooltip Images/FinishStairs.jpg", antisynergy: "Finish"},
	{name: "Blow up an End Crystal"},
	{name: "Never place Torches"},
],

// Very Hard (4)
[
	{name: "WIP challenges"},
	{name: "Cannot craft any Palshperes(even with Pals)", tooltiptext: "Coal, Diamond, Emerald, Gold, Iron, Lapis Lazuli, Nether Quatz and Redstone ores are your choices", tooltipimg: "Goal Tooltip Images/Ores.jpg"},
	{name: "craft a rare outfit", tooltiptext: "Splash variants count! Even Lingering if you want to get crazy"},
	{name: "Bingo Without base", antisynergy:"Bases"},
	// {name: "Every type of Chestplate", tooltiptext: "Leather, Gold, Iron, Diamond and yes, even Chainmail", tooltipimg: "Goal Tooltip Images/chainmail chest.jpg"},
	// {name: "Nether Star"},
	// {name: "Dragon Egg"},
	// {name: "Any mob head OTHER than a Wither Skeleton's", tooltiptext: "Dragon, Skeleton, Zombie or a Creeper Head. Wither Skeleton skulls do NOT count"},
	// {name: "(5-10) Popped Chorus Fruit"},
	// {name: "Every colour of Dye"},
	// {name: "Level (38-50)", antisynergy: "Level", infrequency: 4},
	// {name: "Fill a Double Chest with 3456 items"},
	// {name: "(16-32) Tipped Arrows"},
	// {name: "Place 1 of each Mineral block on top of each other", tooltiptext: "Coal, Iron, Gold, Diamond, Redstone, Lapis, Emerald and Quartz blocks", tooltipimg: "Goal Tooltip Images/MineralBlocks.jpg"},
	// {name: "Save yourself with a Totem of Undying"},
	// {name: "Sleep in a Woodland Mansion"},
]

];
